# coding:utf-8
# @author:nuex,http://handsome.ink
# for centos7 x64  mini install

# 本机ip
IP = "192.168.233.132"

JDK_VERSION = "1.8.0"

# 程序安装路径(和下载的位置相同)
INSTALL_PATH = "/usr/local/soft/"

NGINX_VERSION = "1.2.1"

RUBY_VERSION = "2.4.10"

REDIS_VERSION = "3.2.5"
REDIS_CLUSTER_PORT = ['7001', '7002', '7003', '7004', '7005', '7006']
REDIS_PASSWORD = 'zallsteel'

MYSQL_VERSION = "5.7"
MYSQL_USER_NAME = "root"
MySQL_PASSWORD = "zallsteel"
MySQL_IP_PORT = "127.0.0.1:3306"

APOLLO_VERSION = "1.5.1"
APOLLO_PROTEL_IP = "192.168.233.132"

MAVEN_VERSION = "3.6.1"

FASTDFS_VERSION = "5.05"
LIBFASTCOMMON_VERSION = "1.0.7"

FASTDFS_TRACKER_PORT = "22122"
FASTDFS_TRACKER_BASE_PATH = INSTALL_PATH + "fastdfs/tracker"
FASTDFS_TRACKER_HTTP_SERVER_PORT = "80"
FASTDFS_STORAGE_BASE_PATH = INSTALL_PATH + "fastdfs/storage"
FASTDFS_STORAGE_STORE_PATH0 = INSTALL_PATH + "fastdfs/storage/file"
FASTDFS_STORAGE_TACKER_SERVER = "192.168.233.132:22122"
FASTDFS_STORAGE_HTTP_SERVER_PORT = "80"
FASTDFS_STORAGE_PORT = "23000"
FASTDFS_CLIENT_BASE_PATH = INSTALL_PATH + "fastdfs/client"
FASTDFS_CLIENT_TACKER_SERVER = "192.168.233.132:22122"
FASTDFS_NGINX_MODULE_VERSION = "x"  # 经测试只有x版本不会出错
FASTDFS_NGINX_MODULE_CONNECT_TIMEOUT = "10"
FASTDFS_NGINX_MODULE_TRACKER_SERVER = "192.168.233.132:22122"
FASTDFS_NGINX_MODULE_URL_HAVE_GROUP_NAME = "True"
FASTDFS_NGINX_MODULE_STORE_PATH0 = INSTALL_PATH + "fastdfs/storage/file"

XXL_JOB_ADMIN_MYSQL_IP_PORT = '127.0.0.1:3306'
XXL_JOB_ADMIN_MYSQL_USER = 'root'
XXL_JOB_ADMIN_MYSQL_PWD = 'zallsteel'

ELASTICSEARCH_USER = 'es'  # 新建用户,启动elasticsearch
ELASTICSEARCH_PWD = 'zallsteel'

# 命令与安装方法的映射：必须一一对应
FUNCTION_MAPPING = {'javac': 'i_jdk', 'mysql': 'i_mysql', 'mvn': 'i_maven'}

# 删除下载的压缩包
CLEAR_DOWNLOAD_FILE = 1

# 删除解压后的文件
CLEAR_RELEASE_FILE = 1

# 选择安装的模块
JAVA = 0
APOLLO = 0
APOLLO_PROTEL = 0  # 1安装(apollo-adminservice,apollo-configservice,apollo-portal),0安装(apollo-adminservice,apollo-configservice,)
MYSQL = 0
NGINX = 1
REDIS = 0
RUBY = 0
MAVEN = 0

FASTDFS = 1
FASTDFS_TRACKER = 1
FASTDFS_STORAGE = 1
FASTDFS_CLIENT = 1

XXL_JOB_ADMIN = 0

RABBITMQ = 0

ZOOKEEPER = 0

ELASTICSEARCH = 0
